#!/bin/bash

# todo:
# 0 add a proj dir
# 1 compile using the compiler and the flags
# 2 run simple tests
# 3 run valgrind

# endgame shit:
# run complex tests pattern matching
# scrape other files from project


GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

valgrind="false"
proj_dir=""
defaults="$HOME/.defaults"
compiler=$(grep "compiler: " "$defaults" | sed 's/compiler: //')
flags=$(grep "^flag:" "$defaults" | cut -d ' ' -f 2-)

while getopts "vd:" opt; do
  case $opt in
    v)
      valgrind="true"
      ;;
    d)
      proj_dir="$OPTARG"
      ;;
    \?)
      echo -e "$RED" "Invalid option: -$OPTARG" "$NC"
      exit 1
      ;;
  esac
done

echo "/usr/bin/$compiler$flags$proj_dir -o output_executable"
"$compiler -v"
