#!/bin/bash

# todo:
# 0 add a proj dir
# 1 compile using the compiler and the flags
# 2 run simple tests
# 3 run valgrind

# endgame shit:
# run complex tests pattern matching
# scrape other files from project


GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

valgrind="false"
proj_dir=""
defaults="$HOME/.defaults"
exe_dir="$HOME/.gradescope"
compiler=$(grep "compiler: " "$defaults" | sed 's/compiler: //')
flags=$(grep "^flag:" "$defaults" | cut -d ' ' -f 2-)

while getopts "vd:" opt; do
  case $opt in
    v)
      valgrind="true"
      ;;
    d)
      proj_dir="$OPTARG"
      ;;
    \?)
      echo -e "$RED" "Invalid option: -$OPTARG" "$NC"
      exit 1
      ;;
  esac
done

if [ "$flags" ]; then
  /usr/bin/$compiler $flags $proj_dir -o output_exe
else
  /usr/bin/$compiler $proj_dir -o ~/.output_exe
fi

cd $(dirname $proj_dir)
if [ "$valgrind" ]; then
  $exe_dir/testing -v
else
  $exe_dir/testing
fi

rm ~/.output_exe
