#!/bin/bash

# deal with the flags

# possible flags:
# -f pattern for files
# -t pattern for tests
# -e pattern for expected
# -d project directory
# -j for tests in json

# finished flags:
# -c for compiler
# -a for adding flags
# -r to remove a flag
# -x for remove all
# -l for listing the flags
# -h for help


proj_dir="$HOME/.gradescope"
defaults="$HOME/.defaults"
#get the default compiler and flags
compiler=$(grep "compiler: " "$defaults" | sed 's/compiler: //') 
flags=$(grep "^flag:" "$defaults" | cut -d ' ' -f 2-)

while getopts "c:r:xa:hl" opt; do
  case $opt in
    c)
      compiler="$OPTARG"
      ;;
    a)
      echo "flag: $OPTARG" >> "$defaults"
      flags=$(grep "^flag:" "$defaults" | cut -d ' ' -f 2-)
      ;;
    r)
      echo "compiler: $compiler" > "$defaults"
      echo "$flags" | while read -r flag; do
        if [ "$flag" != "$OPTARG" ]; then
          echo "flag: $flag" >> "$defaults"
        fi
      done
      flags=$(grep "^flag:" "$defaults" | cut -d ' ' -f 2-)
      ;;
    x)
      echo "compiler: $compiler" > "$defaults"
      flags=""
      ;;
    l)
      echo "$flags"
      ;;
    h)
      echo "kill yourself"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# save the compiler and flags
echo "compiler: $compiler" > "$defaults"
echo "$flags" | while read -r flag; do
  if [ -n "$flag" ]; then
    echo "flag: $flag" >> "$defaults"
  fi
done
