#!/bin/bash

# deal with the flags
# possible flags:
# -c for compiler
# -a for adding flags
# -r :flag: for remove a flag
# -r for removing all flags
# -l for listing the flags
# -h for help
# -f pattern for files
# -t pattern for tests
# -e pattern for expected
# -d project directory
# -j for tests in json

# finished flags:

proj_dir="$HOME/.gradescope"
#get the default compiler and flags
compiler=$(grep "compiler: " "$proj_dir/defaults" | sed 's/compiler: //') 

while getopts "c:" opt; do
  case $opt in
    c)
      compiler="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# save the compiler and flags
echo "$compiler"
